language: python
script: "python ./runtests.py"
before_install:
    - sudo apt-get install libssl-dev
install:
    - "pip install Django==$DJANGO"
    - "python setup.py install"
env:
    - DJANGO=1.3.7
    - DJANGO=1.4.5
    - DJANGO=1.5.1
    - DJANGO=1.6.2
    - DJANGO=1.8
python:
    - "2.7"
    - "3.2.3"

matrix:
    exclude:
        - python: "3.2.3"
          env: DJANGO=1.3.7
        - python: "3.2.3"
          env: DJANGO=1.4.5
